/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current user with their personal context, accounts and categories
         * @description Creates the user, their personal context, a default account and the default category set on first call. Idempotent.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transactions of the personal context within a date range */
        get: operations["listTransactions"];
        put?: never;
        /** Record a transaction */
        post: operations["createTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a transaction
         * @description The author may delete their own; the context owner may delete anyone's.
         */
        delete: operations["deleteTransaction"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @example invalid_amount */
            code: string;
            message: string;
        };
        /**
         * @description A positive decimal with at most two fraction digits.
         * @example 1250.00
         */
        Amount: string;
        /**
         * @description ISO 4217 alphabetic code.
         * @example EUR
         */
        Currency: string;
        /** @enum {string} */
        TransactionType: "expense" | "income" | "transfer";
        /** @enum {string} */
        CategoryKind: "expense" | "income";
        User: {
            /** Format: int64 */
            id: number;
            first_name: string;
            username?: string;
            language_code?: string;
            base_currency: components["schemas"]["Currency"];
        };
        Context: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "personal" | "group";
            name: string;
            /** Format: int64 */
            owner_id: number;
            base_currency: components["schemas"]["Currency"];
        };
        Account: {
            /** Format: uuid */
            id: string;
            name: string;
            currency: components["schemas"]["Currency"];
            /** @example 0.00 */
            initial_balance: string;
        };
        Category: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            parent_id?: string | null;
            kind: components["schemas"]["CategoryKind"];
            name: string;
            icon: string;
        };
        Me: {
            user: components["schemas"]["User"];
            context: components["schemas"]["Context"];
            accounts: components["schemas"]["Account"][];
            categories: components["schemas"]["Category"][];
        };
        NewTransaction: {
            type: components["schemas"]["TransactionType"];
            /** Format: uuid */
            account_id: string;
            /** Format: uuid */
            category_id?: string | null;
            amount: components["schemas"]["Amount"];
            /** Format: date */
            occurred_on: string;
            note?: string;
        };
        Transaction: {
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            author_id: number;
            type: components["schemas"]["TransactionType"];
            /** Format: uuid */
            account_id: string;
            /** Format: uuid */
            to_account_id?: string | null;
            /** Format: uuid */
            category_id?: string | null;
            amount: components["schemas"]["Amount"];
            currency: components["schemas"]["Currency"];
            /** @example 1 */
            rate: string;
            /** Format: date */
            occurred_on: string;
            note?: string;
            /** Format: date-time */
            created_at: string;
        };
    };
    responses: {
        /** @description Something went wrong */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listTransactions: {
        parameters: {
            query?: {
                /** @description Inclusive lower bound. Defaults to the first day of the current month. */
                from?: string;
                /** @description Inclusive upper bound. Defaults to today. */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"][];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    createTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewTransaction"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    deleteTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
}
