// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package main

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CategoryKind.
const (
	CategoryKindExpense CategoryKind = "expense"
	CategoryKindIncome  CategoryKind = "income"
)

// Valid indicates whether the value is a known member of the CategoryKind enum.
func (e CategoryKind) Valid() bool {
	switch e {
	case CategoryKindExpense:
		return true
	case CategoryKindIncome:
		return true
	default:
		return false
	}
}

// Defines values for ContextKind.
const (
	Group    ContextKind = "group"
	Personal ContextKind = "personal"
)

// Valid indicates whether the value is a known member of the ContextKind enum.
func (e ContextKind) Valid() bool {
	switch e {
	case Group:
		return true
	case Personal:
		return true
	default:
		return false
	}
}

// Defines values for TransactionType.
const (
	TransactionTypeExpense  TransactionType = "expense"
	TransactionTypeIncome   TransactionType = "income"
	TransactionTypeTransfer TransactionType = "transfer"
)

// Valid indicates whether the value is a known member of the TransactionType enum.
func (e TransactionType) Valid() bool {
	switch e {
	case TransactionTypeExpense:
		return true
	case TransactionTypeIncome:
		return true
	case TransactionTypeTransfer:
		return true
	default:
		return false
	}
}

// Account defines model for Account.
type Account struct {
	// Currency ISO 4217 alphabetic code.
	//
	// Example: EUR
	Currency Currency           `json:"currency"`
	Id       openapi_types.UUID `json:"id"`

	// InitialBalance Example: 0.00
	InitialBalance string `json:"initial_balance"`
	Name           string `json:"name"`
}

// Amount A positive decimal with at most two fraction digits.
//
// Example: 1250.00
type Amount = string

// Category defines model for Category.
type Category struct {
	Icon     string              `json:"icon"`
	Id       openapi_types.UUID  `json:"id"`
	Kind     CategoryKind        `json:"kind"`
	Name     string              `json:"name"`
	ParentId *openapi_types.UUID `json:"parent_id,omitempty"`
}

// CategoryKind defines model for CategoryKind.
type CategoryKind string

// Context defines model for Context.
type Context struct {
	// BaseCurrency ISO 4217 alphabetic code.
	//
	// Example: EUR
	BaseCurrency Currency           `json:"base_currency"`
	Id           openapi_types.UUID `json:"id"`
	Kind         ContextKind        `json:"kind"`
	Name         string             `json:"name"`
	OwnerId      int64              `json:"owner_id"`
}

// ContextKind defines model for Context.Kind.
type ContextKind string

// Currency ISO 4217 alphabetic code.
//
// Example: EUR
type Currency = string

// Error defines model for Error.
type Error struct {
	// Code Example: invalid_amount
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Me defines model for Me.
type Me struct {
	Accounts   []Account  `json:"accounts"`
	Categories []Category `json:"categories"`
	Context    Context    `json:"context"`
	User       User       `json:"user"`
}

// NewTransaction defines model for NewTransaction.
type NewTransaction struct {
	AccountId openapi_types.UUID `json:"account_id"`

	// Amount A positive decimal with at most two fraction digits.
	//
	// Example: 1250.00
	Amount     Amount              `json:"amount"`
	CategoryId *openapi_types.UUID `json:"category_id,omitempty"`
	Note       *string             `json:"note,omitempty"`
	OccurredOn openapi_types.Date  `json:"occurred_on"`
	Type       TransactionType     `json:"type"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	AccountId openapi_types.UUID `json:"account_id"`

	// Amount A positive decimal with at most two fraction digits.
	//
	// Example: 1250.00
	Amount     Amount              `json:"amount"`
	AuthorId   int64               `json:"author_id"`
	CategoryId *openapi_types.UUID `json:"category_id,omitempty"`
	CreatedAt  time.Time           `json:"created_at"`

	// Currency ISO 4217 alphabetic code.
	//
	// Example: EUR
	Currency   Currency           `json:"currency"`
	Id         openapi_types.UUID `json:"id"`
	Note       *string            `json:"note,omitempty"`
	OccurredOn openapi_types.Date `json:"occurred_on"`

	// Rate Example: 1
	Rate        string              `json:"rate"`
	ToAccountId *openapi_types.UUID `json:"to_account_id,omitempty"`
	Type        TransactionType     `json:"type"`
}

// TransactionType defines model for TransactionType.
type TransactionType string

// User defines model for User.
type User struct {
	// BaseCurrency ISO 4217 alphabetic code.
	//
	// Example: EUR
	BaseCurrency Currency `json:"base_currency"`
	FirstName    string   `json:"first_name"`
	Id           int64    `json:"id"`
	LanguageCode *string  `json:"language_code,omitempty"`
	Username     *string  `json:"username,omitempty"`
}

// ListTransactionsParams defines parameters for ListTransactions.
type ListTransactionsParams struct {
	// From Inclusive lower bound. Defaults to the first day of the current month.
	From *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`

	// To Inclusive upper bound. Defaults to today.
	To *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`
}

// CreateTransactionJSONRequestBody defines body for CreateTransaction for application/json ContentType.
type CreateTransactionJSONRequestBody = NewTransaction
